name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check FTP credentials
        run: |
          if [ -z "$TEST_VALUE" ]; then
             echo "TEST_SECRET is EMPTY"
          else
            echo "TEST_SECRET is available"
          fi
        env:
          TEST_VALUE: ${{ secrets.TEST_SECRET }}

      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.varadesigns.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /public_html/test/